# Common Variables
variable "resource_group" {
  description = "target resource group resource mask"
  type = object({
    name     = string
    location = string
  })
  default = {
    name = "deb-test-devops"
    location = "eastus"
  }
}

variable "storage_account" {
    description = "The storage account associated with the function app"
    type = object ({
        name = string
        rg_name = string
    })
}

variable "application_insights" {
    description = "The Application Insights associated with the function app"
    type = object ({
        name = string
        rg_name = string
    })
}

variable "service_plan" {
    description = "The Service Plan associated with the function app"
    type = object ({
        name = string
        rg_name = string
    })
}

variable "container_registry" {
    description = "The Container Registry associated with the function app. Required only when application_stack = docker"
    type = object ({
        name = string
        rg_name = string
    })

    default = {
        name = ""
        rg_name = ""
    }
}


# Variables related to function app

variable "function_app_name" {
    description = "Function app name generated by resource name module"
}
variable "application_stack" {
    description = "One of these options - docker, dotnet, java, node, python, powershell, custom"
    default = "docker"
}

variable "docker_image_name" {
    description = "The docker image name. Required only when application_stack = docker"
    default = "sample-functions"
}

variable "docker_image_tag" {
    description = "The docker image tag. Required only when application_stack = docker"
    default = "1001"
}

variable "dotnet_version" {
    default = null
    description = "Dotnet version for function runtime. Required only when application_stack = dotnet. Must be 3.1 or 6.0"
}

variable "java_version" {
    default = null
    description = "Dotnet version for function runtime. Required only when application_stack = java"
}

variable "node_version" {
    default = null
    description = "Dotnet version for function runtime. Required only when application_stack = node"
}

variable "python_version" {
    default = null
    description = "Dotnet version for function runtime. Required only when application_stack = python"
}

variable "powershell_version" {
    default = null
    description = "Powershell Core version for function runtime. Required only when application_stack = powershell"
}

variable "use_custom_runtime" {
    default = false
    description = "Is there a custom runtime for the function. Required only when application_stack = custom"
    type = bool
}

variable "site_config" {
    description = "All the site config mentioned in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app#site_config except application_stack"
    type = any
    default = {}
}

variable "application_settings" {
    description = "The environment variables passed in to the function app"
    type = map(string)
    default = {}
}

variable "connection_strings" {
    description = "List of connection strings (name, type, value)"
    type = list(object({
        name = string
        type = string
        value = string
    }))
    default = []
}

variable "cors" {
    description = "CORS block (allowed_origins, support_credentials)"
    type = object({
        allowed_origins     = list(string)
        support_credentials = bool
    })
    default = null
}

variable "custom_tags" {
    description = "Custom Tags"
    type = map(string)
    default = {}
}

## Variables related to Deployment Slots

variable "deployment_slots" {
    description = "Name of the deployment slots"
    type = list(string)
    default = []
}


